app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
	'uses'=>'FrontController@index',
	'as'=>'/'
	]);

Route::get('categories/{name}',[
	'uses'=>'FrontController@searchCategory',
	'as'  => 'search.category'
	]);

Route::get('tags/{name}',[
	'uses'=>'FrontController@searchTags',
	'as'  => 'search.tags'
	]);
Route::get('articles/{slug}',[
		'uses' => 'FrontController@viewArticle',
		'as'   => 'articles.view'
	]);

Route::group(['prefix'=>'admin','middleware'=>['auth']],function(){
	
	Route::group(['middleware'=>'admin'],function(){

		Route::resource('users','UsersController');
		
		Route::get('users/{id}/destroy',[
		'uses'=>'UsersController@destroy',
		'as'=>'admin.users.destroy'
		]);

	});
	
	Route::resource('categories','CategoriesController');
	Route::resource('tags','TagsController');
	Route::resource('articles','ArticlesController');

	

	Route::get('categories/{id}/destroy',[
		'uses'=>'CategoriesController@destroy',
		'as'=>'admin.categories.destroy'
		]);

	Route::get('tags/{id}/destroy',[
		'uses'=>'tagsController@destroy',
		'as'=>'admin.tags.destroy'
		]);

	Route::get('articles/{id}/destroy',[
		'uses'=>'ArticlesController@destroy',
		'as'=>'admin.articles.destroy'
		]);

	Route::get('images',[
		'uses'=>'ImageController@index',
		'as' => 'admin.images.index'
		]);
	
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('admin/auth/login',[
	'uses'=>'Auth\AuthController@getLogin',
	'as'=>'admin.auth.login'
	]);

Route::post('admin/auth/login',[
	'uses'=>'Auth\AuthController@postLogin',
	'as'=>'admin.auth.login'
	]);

Route::get('admin/auth/logout',[
	'uses'=>'Auth\AuthController@logout',
	'as'=>'admin.auth.logout'
	]);

resources/views/admin/template/partials/erros.blade.php
@if(count($errors)>0)
<div class="alert alert-danger alert-important">
		<ul>
			@foreach($errors->all() as $error)
				<li>{{$error}}</li>
			@endforeach()
		</ul>
</div>
@endif

resources/views/admin/template/partials/nav.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{route('/')}}">Blog</a>
    </div>


    

     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      @if(Auth::user())
      
      @if(Auth::user()->isAdmin())
      <ul class="nav navbar-nav">  
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Usuarios<span class="caret"></span></a>
          <ul class="dropdown-menu">
             <li class="active"><a href="{{route('admin.users.index')}}">Lista de usuarios<span class="sr-only">(current)
            <li role="separator" class="divider"></li>
            <li><a href="{{route('admin.users.create')}}">Crear usuario</a></li>
          </ul>
        </li>
      </ul>
      @endif
    
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categorias<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{route('admin.categories.index')}}">Lista de categorias</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{{route('admin.categories.create')}}">Crear categorias</a></li>
          </ul>
        </li>
      </ul>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Etiquetas<span class="caret"></span></a>
          <ul class="dropdown-menu">
  
            <li><a href="{{route('admin.tags.index')}}">Lista de etiquetas</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{{route('admin.tags.create')}}">Crear etiquetas</a></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Articulos<span class="caret"></span></a>
          <ul class="dropdown-menu">
  
             <li><a href="{{route('admin.articles.index')}}">Lista de articulos</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{{route('admin.articles.create')}}">Crear Articulo</a></li>
          </ul>
        </li>
        <li><a href="{{ route('admin.images.index')}}">Imagenes</a></li>
      </ul>
      
  @endif



<!-- Authentication Links -->
      <ul class="nav navbar-nav navbar-right">
        @if (Auth::guest())
          <li><a href="{{ url('/login') }}">Entrar</a></li>
          <li><a href="{{ url('/register') }}">Registrarse</a></li>
        @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Salir</a></li>
                            </ul>
                        </li>
                    @endif

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>